# Generated by Django 3.1.7 on 2021-02-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField(max_length=3)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=15)),
                ('provincia', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
